export const ActionTypes = {
    // ?Order
    SET_ORDER : "SET_ORDER",
    SELECTED_ORDER: "SELECTED_ORDER",
    MODAL_MANAGE_ORDER:"MODAL_MANAGE_ORDER",
    HANDLER_FORM_ITEM:"HANDLER_FORM_ITEM",
   
    SET_PRODUCT:"SET_PRODUCT",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    
}